#!/bin/bash
set -e

echo "========================================"
echo "sys_stats Cloudflare Pages Deployer"
echo "========================================"

echo "Building WebAssembly frontend..."
cd frontend-app
# Ensure we build for the web platform in release mode
~/.cargo/bin/dx build --platform web --release

echo "Deploying to Cloudflare Pages..."
# Use Wrangler to deploy the output directory generated by dx build
npx wrangler pages deploy ../target/dx/frontend-app/release/web/public --project-name sysstats-ui

echo "========================================"
echo "Deployment Complete!"
echo "Your dashboard is now live on the Edge."
echo "========================================"
